### ISSUE TITLE
Ignore scsslint_tmp files in sass watch?

### ISSUE THREAD

**Issue by peterjmag** [idok/scss-lint-plugin#13]
I currently get a bit of extra noise using this plugin while running `sass --watch`:

    [exec] >>> Change detected to: styles/scss/testfile.scss
    [exec] >>> Deleted template detected: styles/scss/testfile_scsslint_tmp5738996101794459734.scss
    [exec]      delete /Users/peterjmag/checkouts/scss-lint-test/styles/testfile_scsslint_tmp5738996101794459734.css
    [exec]      delete /Users/peterjmag/checkouts/scss-lint-test/styles/testfile_scsslint_tmp5738996101794459734.css.map
    [exec]       write /Users/peterjmag/checkouts/scss-lint-test/styles/testfile.css
    [exec]       write /Users/peterjmag/checkouts/scss-lint-test/styles/testfile.css.map
    [exec] >>> Change detected to: styles/scss/testfile.scss

Unfortunately, sass doesn't appear to support explicitly ignoring files. Perhaps we can simply add an underscore before [the baseName in ThreadLocalActualFile.java](https://github.com/idok/scss-lint-plugin/blob/46c7cd73967872aa9bcdcd22af357be1853f3801/intellij-common/src/com/wix/ThreadLocalActualFile.java#L71)? Then theoretically the scsslint_tmp files would be [ignored as a partial](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials).

I would try this out myself, but I'm having trouble building the plugin locally at the moment. (Just problems with my environment, I believe.)

**Comment by JacobDorman** [comment]
Partials are still watched, just not compiled into their own separate css file. So this wouldn't fix the issue.

Is there a reason these need to be created in the working directory, rather than say the system temp dir?

If you use grunt you can just ignore the pattern ```!sass/**/*scsslint*.scss```

**Comment by SpenceDiNicolantonio** [comment]
This has been a source of headache for me recently (juanfran/gulp-scss-lint#36). These temp files really should be stored elsewhere.

**Comment by siiron** [comment]
Having the same issue here. The scsslint_tmp-files triggers my watch-task while editing my scss-files since they appear in my working directory instead of a different folder. It's a bit annoying. Since I use grunt, It still works to exclude them from the watch-task with something like `!sass/**/*scsslint_tmp*.scss`.

**Comment by gebidesign** [comment]
I've just spent an hour trying to figure out why my webpack server was reloading like crazy on each keystroke in scss files. Well, now it appears it's just scss lint that creates a temp file, triggering the server to reload. 

Here's a quick fix for gulp to ignore those files:
```js
gulp.watch('**/*.scss',
           '!**/*scsslint_tmp*.scss']);
```

**Comment by idok** [comment]
I've moved the temp files to a temp directory, this should resolve this issue

**Comment by AndyOGo** [comment]
I have this problem with PHPStorm (newest version) +Gulp and get these weird tmp files for my js files.
Yes `.js`not `.scss`...

It's horrible it creates those tmp files inside source dir, and `scsslint` for js files does not make any sense...

`tasks/docs-scripts_scsslint_tmp1537225672253761620.js`
`tasks/scripts-bundle_scsslint_tmp4377624646903046346.js`

**Comment by idok** [comment]
@AndyOGo 
Which version of scss-lint-plugin do you have?
do you have other plugins enabled? 
specifically something from this [list](https://plugins.jetbrains.com/space/index?pr=&lg=kokoMonkey)
please disabled them and retry.

**Comment by AndyOGo** [comment]
I use eslint, but I have set it up to use my local eslint module specified within my package.json file
