### ISSUE TITLE
Error highlights doesn't highlight whole error

### ISSUE THREAD

**Issue by bobrocke** [idok/scss-lint-plugin#21]
Errors have background highlighting only partially applied:

![www grav dev - phpstorm ps-141 1717](https://cloud.githubusercontent.com/assets/2962426/8396211/d4f86b58-1d6a-11e5-960b-dd2303cc5ead.jpg)

PhpStorm EAP 1717

**Comment by idok** [comment]
which version of scss-lint and scss-lint-plugin are you using?

**Comment by idok** [comment]
Still relevant?

**Comment by bobrocke** [comment]
I don't use the plug-in any more, so no.
