### ISSUE TITLE
Choose button disabled on Path To Executable

### ISSUE THREAD

**Issue by monte-hayward** [idok/scss-lint-plugin#25]
How do I designate the executable

Near as I can tell, the "executable" is here:
/Users/monte/Library/Application Support/WebStorm11/scss-lint-plugin/lib/scss-lint-plugin.jar

However, when I navigate to that location, the jars are not selectable.
This is true with or without `chmod +x *.jar`

The directories enable "Choose" button, but then choose just opens the directory, and the buttons is again disabled/

**Comment by monte-hayward** [comment]
fwiw, Webstorm 11 EAP is the IDE in question

**Comment by monte-hayward** [comment]
I managed to paste in the path, instead of navigate.
No love
I then tried "install plugin from file", and pointed out the zip file, which Webstorm accepted.
chmod +x *.jar

Then, opening an scss file, I got this:
/Users/me/Library/Application Support/WebStorm11/scss-lint-plugin/lib/scss-lint-plugin.jar: /Users/me/Library/Application Support/WebStorm11/scss-lint-plugin/lib/scss-lint-plugin.jar: cannot execute binary file

**Comment by idok** [comment]
The required executable path is the scss-lint execuable, for example: /usr/bin/scss-lint
