### ISSUE TITLE
Option to read the config file of the current project in WebStorm

### ISSUE THREAD

**Issue by gunnx** [idok/scss-lint-plugin#27]
What is the behaviour of option 'Let scss-lint search for config up the folder tree' ?

Is that folder relative to the SCSS Lint exe or your current project folder ?

When I set it, it does not pick up my .scss-lint.yaml file config, I would like this option so I don't need to update this everytime I switch projects.

**Comment by idok** [comment]
By choosing this option, you are NOT passing a config file to scss-lint and letting it use the following behaviour:
https://github.com/brigade/scss-lint/#configuration
I agree it is not clear from the label.

**Comment by gunnx** [comment]
@idok  Ok thanks that makes more sense. Is it possible in your plugin for there to be an option to search the current active project workspace in WebStorm. 
This would be similar to how JSHint works, it searches up from the current file its linting.

**Comment by idok** [comment]
The plugin runs scss-lint from the command line either passing a config file or not.
When you open the drop down for config file, you get all config files from your project.
