### ISSUE TITLE
intellij idea 15 strange behaviour

### ISSUE THREAD

**Issue by evilebottnawi** [idok/scss-lint-plugin#28]
Whne i open file, scss-lint not applied, but if i change content and upload file on server scss-lint run. While i push button to save file on server scss-lint not run and i not see errors

**Comment by manuelbostanci** [comment]
I have the same problem! 
Plugin is correctly configured but not working with IntelliJ 15.

**Comment by idok** [comment]
Can you supply more details?

**Comment by idok** [comment]
should be fixed with version 1.1.0
