### ISSUE TITLE
Effort needed to implement stylelint or sass-lint

### ISSUE THREAD

**Issue by dwightjack** [idok/scss-lint-plugin#29]
Hi,
this plugin works great for me, but since my stack doesn't include Ruby I'd like to know what it could be the effort to implement alternative linters as postCSS [stylelint](https://github.com/stylelint/stylelint) or [sass-lint](https://github.com/sasstools/sass-lint).

Stylelint already has atom sublime and visual studio code plugins. I've never developed a pluign for webstorm so it's difficult to understand if it'd be a good idea to add a "select your linter" options (and all the logic of multiple linters) or it'd be better to start with a new project.

Thanks in advance

**Comment by stevenjlho** [comment]
+1

**Comment by glen-84** [comment]
+1 for sass-lint

**Comment by idok** [comment]
This is actually not an issue with scss-lint-plugin or even a feature request, but rather a request for a new plugin.
I'll check sass-lint and stylelint.

**Comment by dwightjack** [comment]
Ok thanks!

As I wrote before, I never coded a webstorm plugin, but I may help im any way just ping me.

**Comment by idok** [comment]
Very rough first version, enjoy
https://github.com/idok/sass-lint-plugin

**Comment by stevenjlho** [comment]
Thanks for your effort.

**Comment by dwightjack** [comment]
Thanks! 

I've installed it and will test it on my current project.
As of now it's working fine. Will report any issue in the plugin repo.

Bye!

**Comment by glen-84** [comment]
Awesome! Thank you so much. =)
