### ISSUE TITLE
All warnings disappear after fixing first warning.

### ISSUE THREAD

**Issue by DaveBagler** [idok/scss-lint-plugin#32]
When I open a scss file the plugin inspects the code and displays all the warnings, however after I fix one of the warnings (any one of them) all the warnings disappear until I close and reopen the scss file or wait about 30 seconds. It doesn't seem like much but waiting that long between fixing each warning really slows me down.  Is this the expected behaviour? (is the delay just the lint re-running on the updated file?) or is something up?

I'm using PHPStorm version 10.0.3, scss-lint plugin version 1.0.15 and scss-lint gem version 0.44.0.

Thanks for this plugin it really helps make my scss code much more consistent.

**Comment by jsheffers** [comment]
This is happening for me as well on PHPStorm 10.0.2 / scss-lint gem 0.47.1 / scss-lint-plugin 1.0.15

**Comment by gilbarbara** [comment]
Same thing here using PHPStorm 2016.1RC but this has been happening for a few months.

**Comment by julpat** [comment]
+1

**Comment by MistrFana** [comment]
+1

**Comment by gilbarbara** [comment]
There's a new version (1.0.16) today on the plugin registry but nothing changed here on github.
Still, this bug continues.

**Comment by idok** [comment]
Didn't push yet, version 1.0.16 contains a fix, please try it out.

**Comment by idok** [comment]
Fixed
