### ISSUE TITLE
PyCharm problem

### ISSUE THREAD

**Issue by jengdal** [idok/scss-lint-plugin#4]
I'm getting this error after installing the plugin in PyCharm:

    Plugin "scss-lint" was not loaded: required plugin "org.jetbrains.plugins.yaml" not installed.

I can't find a yaml plugin in the repositories.

PyCharm version: 4 (and at least the one before 4).
Plugin version: 1.0.9.

**Comment by justin808** [comment]
Any fix for this?

**Comment by idok** [comment]
Thanks for the feedback.
Removed YAML dependency, an update will be available soon.

**Comment by jengdal** [comment]
Thanks!
