### ISSUE TITLE
/usr/bin/env: ruby_executable_hooks: No such file or directory

### ISSUE THREAD

**Issue by peric** [idok/scss-lint-plugin#41]
### Versions

scss-lint version: 0.48.0
OS: Linux Mint 17.3 Rosa
IDEA product and version: Rubymine 8.0.4

### Description

/usr/bin/env: ruby_executable_hooks: No such file or directory
![image](https://cloud.githubusercontent.com/assets/1193864/15743546/aabfcd14-28c6-11e6-8570-2e09345c59aa.png)

### Steps to Reproduce

I've enabled SCSS Lint plugin, and added "/home/user/.rvm/gems/ruby-2.2.2/bin/scss-lint" as an "SCSS Lint exe". After I save it, I get the notice from the above and plugin is not working.

Any idea what is causing that issue?

**Comment by tomek-f** [comment]
try `/home/user/.rvm/gems/ruby-2.2.2/wrappers/scss-lint`

http://stackoverflow.com/questions/26247926/how-to-solve-usr-bin-env-ruby-executable-hooks-no-such-file-or-directory

**Comment by peric** [comment]
It works. Even though I was almost sure I've tried that solution before and it didn't work. Well, thanks :)
