### ISSUE TITLE
Wrong yml file in path crashes plugin forever

### ISSUE THREAD

**Issue by lukKowalski** [idok/scss-lint-plugin#44]
I've setup plugin with paths etc. but by mistake i've picked wrong yml file for settings and now i cant change it in sass-lint preferences, event if i uninstall/reinstall/reset this plugin. Every time i see this:
![image](https://cloud.githubusercontent.com/assets/2960003/17552952/63211ce2-5f03-11e6-94c3-b16f77974611.png)

and can't do nothing about it. Is there a way to hard-reset this plugin settings so i could set them up again properly?

WebStorm

**Comment by UFOMelkor** [comment]
Removing `.idea/sasslintPlugin.xml` should allow you to reconfigure the plugin.

**Comment by idok** [comment]
This project is for SCSS Lint, your plugin is SASS lint
See https://github.com/idok/sass-lint-plugin/issues/4#issuecomment-220408563
