### ISSUE TITLE
how do you configure this on windows?

### ISSUE THREAD

**Issue by chrisathook** [idok/scss-lint-plugin#48]
your directions say to path to the executable but this is a gem. it does not have a .exe file.

**Comment by Dinkh** [comment]
Same here. I cannot make it working. My settings:

1. Not working with this setting:
![1](https://cloud.githubusercontent.com/assets/658372/20176843/f95b4d3e-a749-11e6-9f51-0546a7fc2b99.png)

2. Not showing plugin version, but not showing "error" (still not working):
![2](https://cloud.githubusercontent.com/assets/658372/20176856/0f79a610-a74a-11e6-92c3-3213428e0e1d.png)

3. Not validating, as you can see in this screenshot:
![3](https://cloud.githubusercontent.com/assets/658372/20176866/23f03e9c-a74a-11e6-97c9-049d434a45d9.png)

4. Validating in console:
![4](https://cloud.githubusercontent.com/assets/658372/20176877/3389c756-a74a-11e6-9e22-6f1b2b8bef1d.png)

Can anyone help?

**Comment by czubehead** [comment]
Same issue here

**Comment by idok** [comment]
It should be:  [rubypath]\bin\scss-lint.bat)
I've updated the readme
https://github.com/idok/scss-lint-plugin/blob/master/README.md#settings
