### ISSUE TITLE
Add ability to disable showing "SCSS Lint is available for this file but is not configured"

### ISSUE THREAD

**Issue by Splaktar** [idok/scss-lint-plugin#62]
### Versions

scss-lint version: [N/A]
You can get this information from executing `scss-lint --version` at the command line.

OS: [macOS Mojave]
IDEA product and version: [e.g. webstorm 2018.2.6]

### Description

No option to hide the "SCSS Lint is available for this file but is not configured" messages.

### Steps to Reproduce

1. Install and enable plugin
2. Open a project that isn't using SCSS Lint
3. Open a SCSS file
4. Open SCSS Lint settings...
5. Look for an option to disable showing the message "SCSS Lint is available for this file but is not configured"

**Expected behavior:** There is an option to hide the prompts for "SCSS Lint is available for this file but is not configured".

**Actual behavior:** There is no such option.

Thank you for your work on this plugin!

**Comment by Kovah** [comment]
Yes please. I have to enable SCSS Lint for one project and now in every other project PhpStorm shows the SCSS Lint notification that I can not close or disable. I have to disable the whole plugin to remove this.

**Comment by idok** [comment]
you can disable it from the settings menu in version 2.1.0

**Comment by Splaktar** [comment]
It seems like you have to disable it twice. You need to disable the plugin and also check "Dismiss configuration hints".

When clicking on OK in the menu, I get this:
```java
com.intellij.execution.ExecutionException: Executable is not specified
```
I'm also getting this exception every time that I open a `.scss` file, even when "Enable" is unchecked and "Dismiss configuration hints" is checked.

With this config:
![Screen Shot 2019-08-18 at 12 16 46](https://user-images.githubusercontent.com/3506071/63227203-18726380-c1b2-11e9-8e24-6ce3326cf7ed.png)

I still see:
![Screen Shot 2019-08-18 at 12 12 19](https://user-images.githubusercontent.com/3506071/63227204-1a3c2700-c1b2-11e9-8a21-afdd5b5f887e.png)

**Comment by Brent7788** [comment]
> Do you need to disable the plugin and also check "Dismiss configuration hints"? That still doesn't quite seem to be working.
> 
> When clicking on OK in the menu, I get this:
> 
> ```java
> com.intellij.execution.ExecutionException: Executable is not specified
> ```
> 
> I'm also getting this exception every time that I open a `.scss` file, even when "Enable" is unchecked and "Dismiss configuration hints" is checked.
> 
> With this config:
> ![Screen Shot 2019-08-18 at 12 16 46](https://user-images.githubusercontent.com/3506071/63227203-18726380-c1b2-11e9-8e24-6ce3326cf7ed.png)
> 
> I still see:
> ![Screen Shot 2019-08-18 at 12 12 19](https://user-images.githubusercontent.com/3506071/63227204-1a3c2700-c1b2-11e9-8a21-afdd5b5f887e.png)

I have the same problem.

**Comment by alfiqmiq** [comment]
> you can disable it from the settings menu in version 2.1.0

where i can find this option
![image](https://user-images.githubusercontent.com/9507245/132993553-254c72e0-55fd-43e0-85df-b0141556093e.png)

![image](https://user-images.githubusercontent.com/9507245/132993586-4c78a4d9-07f0-4120-a286-55bd6481785a.png)

still have

![image](https://user-images.githubusercontent.com/9507245/132993608-c2ed3470-b303-40b7-97ca-e8f61739cc40.png)

it's annoing
